### ISSUE TITLE
ipython error in non-spyder terminals

### ISSUE THREAD

**Issue by drsmith48** [Fusion-Data-Framework/fdf#19]
@jcschmitt @ktritz 
I get the following errors when I run iPython in non-Spyder terminals.

```
[sunfire07:~] % ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[TerminalIPythonApp] WARNING | Error in loading extension: kernmagic
Check your config files in /u/drsmith/.ipython/profile_default
Traceback (most recent call last):
  File "/p/fdf/anaconda/lib/python2.7/site-packages/IPython/core/shellapp.py", line 267, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/p/fdf/anaconda/lib/python2.7/site-packages/IPython/core/extensions.py", line 89, in load_extension
    __import__(module_str)
ImportError: No module named kernmagic
```

The same error happens in terminal and X11 on my Mac and in non-spyder terminals in nomachine.  Any thoughts?

**Comment by ktritz** [comment]
Try
from fdf import factory

I don't think the init file is set up properly.

**Comment by drsmith48** [comment]
sorry - the fdf error in the original comment was user (me) error.  the ipython error is real, though.

**Comment by ktritz** [comment]
Ah, find the line

c.TerminalIPythonApp.extensions = ['kernmagic']

in your ipython_config.py file in  /u/drsmith/.ipython/profile_default

and comment it out.

**Comment by drsmith48** [comment]
great, thanks.
